"""add_recommended_pipeline_to_documents

Revision ID: 282e1c4b5c4f
Revises: 364237e654b4
Create Date: 2025-08-20 12:05:11.478772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '282e1c4b5c4f'
down_revision: Union[str, Sequence[str], None] = '364237e654b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('recommended_pipeline', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'recommended_pipeline')
    # ### end Alembic commands ###
