"""Add context_chunks to QACache

Revision ID: c252542b2d4a
Revises: 
Create Date: 2025-08-01 10:11:41.085540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c252542b2d4a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qa_cache_id'), table_name='qa_cache')
    op.drop_index(op.f('ix_qa_cache_question'), table_name='qa_cache')
    op.drop_table('qa_cache')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qa_cache',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('context', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('embedding_model', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hit_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('qa_cache_pkey'))
    )
    op.create_index(op.f('ix_qa_cache_question'), 'qa_cache', ['question'], unique=True)
    op.create_index(op.f('ix_qa_cache_id'), 'qa_cache', ['id'], unique=False)
    # ### end Alembic commands ###
